# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjA1OTQzMTBhMDdhN2RhNWQ1YWQxMTI0NjhmYjc3NjZlOWYyYmU4MWFlNGMxNmE5ODE3NDJjNjA5Nzc2ZTQ5ZDNiNDAzZTNkMjk4MTViYTFiMzNlNGRkZjY1N2YyMTY2MmFiNjkwMWQyNGJhY2Y4YTk2YjhmMGY1YjI0MTZmZjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
